slam_gmapping:
  ros__parameters:
    throttle_scans: 1
    base_frame: "base_link"
    map_frame: "map"
    odom_frame: "odom"
    transform_publish_period: 0.05
    map_update_interval: 0.5
    maxUrange: 80.0
    maxRange: 0.0
    minimum_score: 0.0
    sigma: 0.05
    kernelSize: 1
    lstep: 0.05
    astep: 0.05
    iterations: 5
    lsigma: 0.075
    ogain: 3.0
    lskip: 0
    srr: 0.1
    srt: 0.2
    str: 0.1
    stt: 0.2
    linearUpdate: 1.0
    angularUpdate: 0.5
    temporalUpdate: 1.0
    resampleThreshold: 0.5
    particles: 30
    xmin: -10.0
    ymin: -10.0
    xmax: 10.0
    ymax: 10.0
    delta: 0.05
    occ_thresh: 0.25
    llsamplerange: 0.01
    llsamplestep: 0.01
    lasamplerange: 0.005
    lasamplestep: 0.005
    tf_delay: 0.05
